# Run with:
# docker compose -f scripts/docker/compose.yml up --build
services:
  openpi_server:
    image: openpi_server
    build:
      context: ../..
      dockerfile: scripts/docker/serve_policy.Dockerfile
    init: true
    tty: true
    network_mode: host
    # Populate configured openpi data home to /openpi_assets inside the container.
    # Populate aws credential inside the container.
    volumes:
      - $PWD:/app
      - ${OPENPI_DATA_HOME:-~/.cache/openpi}:/openpi_assets
    environment:
      - SERVER_ARGS
      - OPENPI_DATA_HOME=/openpi_assets
      - IS_DOCKER=true

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  openpi_dev:
    image: openpi_dev
    build:
      context: ../..
      dockerfile: scripts/docker/serve_policy.Dockerfile
    init: true
    tty: true
    stdin_open: true
    network_mode: host
    # Populate configured openpi data home to /openpi_assets inside the container.
    # Populate aws credential inside the container.
    # Populate huggingface credentials inside the container.
    volumes:
      - $PWD:/app
      - ${OPENPI_DATA_HOME:-~/.cache/openpi}:/openpi_assets
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface

    environment:
      - SERVER_ARGS
      - OPENPI_DATA_HOME=/openpi_assets
      - IS_DOCKER=true
      - HF_TOKEN

    # default command, just open a bash shell
    entrypoint: ["/bin/bash"]

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]